$(function(){$("#datepicker").datepicker({changeMonth:!0,changeYear:!0,minDate:new Date})});
function saveMeeting(){$("#meeting_success").html("");var a=$("#meeting_title").val();if(""==a)return $.msgBox({title:"Alert",content:"Enter meeting name"}),!1;var b=$("input[name='data[meetings][users][]']:checked"),c=[];$.each(b,function(){c.push($(this).val())});if(""==c)return $.msgBox({title:"Alert",content:"Select Users"}),!1;b=$("#datepicker").val();if(""==b)return $.msgBox({title:"Alert",content:"Select meeting date"}),!1;var e=$("#hh").val(),d=$("#minutes").val();$("#metting-email-loader").show();
$.ajax({type:"POST",url:site_url1+"meetings/saveMeeting",data:{friends:c,meeting_title:a,meeting_start_date:b,meeting_start_hours:e,meeting_start_minutes:d}}).done(function(a){$("#metting-email-loader").hide();$("#meeting_success").html(a)});return!1}function list_meetings(){var a=site_url1+"meetings/userMeetings";$("#metting-loader").show();$.ajax({type:"POST",url:a,data:"",datatype:"json",success:function(a){$("#metting-loader").hide();$("#meeting_area").html(a)},error:function(){}})}
function list_meetingsBYAjax(){$.ajax({type:"POST",url:site_url1+"meetings/userMeetings",data:"",datatype:"json",success:function(a){$("#meeting_area").html(a)},error:function(){}})}
function joinmeeting(a,b){$.ajax({type:"POST",url:site_url1+"meetings/CheckActiveMeeting",data:{id:a,roomname:b}}).done(function(c){if("0"==c)return $.msgBox({title:"Alert",content:"Meeting time expired, please refresh the tab."}),!1;$(".right-area").show();c=$("#chatarea").children(".chatarea-inner:visible").length;var e=$("#chatarea").children(".chatarea-inner:visible").length;if(4>e)var d=215*(e+1);0==e&&(d=215);$("#chatarea").css("min-width",d+"px");if(1==c||1<c)$("#chatarea").children(".chatarea-inner").removeClass("one-inner"),
$("#chatarea").removeClass("chatarea-wrapper-main");$("#joinmetting_"+b).hide();$("#chatarea div:visible");roomArray.push(b);c>=maxChatWnd&&($("#par_"+roomArray[i]).hide(),void 0!=roomArray[i]&&$("#active_chats ul").append("<li class='prq' id='li_"+roomArray[i]+"' style='cursor:pointer;' ><span>Group Name "+roomArray[i]+"&nbsp;&nbsp;&nbsp;&nbsp;<input type='image' onclick=reOpenChat('"+roomArray[i]+"') src='"+site_url1+"img/gpchat.png'></span></li>"),i+=1);d='<div id="par_'+b+'" style="float:left;margin-right: 11px;" class="chatarea-inner"><div class="chatarea" id="chatwindow'+
b+'" style="float:left;"><iframe src="'+(site_url1+"meetings/meetingChat/"+a)+'" width="200" height="340" scrolling="no" frameBorder="0"></iframe></div><div class="chatwindowMax" id="chatwindowMax'+b+'" style="display:none;">Max</div></div>';$("#chatarea").append(d);1==$("#chatarea").children(".chatarea-inner").length&&($("#chatarea").children(".chatarea-inner").addClass("one-inner"),$("#chatarea").addClass("chatarea-wrapper-main"));$("#rd"+a).hide()})}
function showChatMeetingDiv(){$("#meeting_area").is(":visible")?$("#meeting_area-wrapper .slimScrollDiv").animate({height:"0px"},500):$("#meeting_area-wrapper .slimScrollDiv").animate({height:"150px"},500);$("#meeting_area").toggle("slow",function(){showhidetogglearea("meeting_area","chat_meetings_max","chat_meetings_min");$("#chat_meetings_max").is(":visible")?(list_meetings(),$("#meeting_area").slimscroll({height:"150px"}),$.ajax({type:"POST",url:site_url1+"meetings/markNotificationAsRead",data:{}}).done(function(a){$("#chat_meetings_max").hide();
$("#chat_meetings_min").show()})):$("#chat_meetings_min").is(":visible")&&($("#chat_meetings_min").hide(),$("#chat_meetings_max").show());$("#list-meetings").toggle()})}function acceptMeetingInvitaion(a,b){$.ajax({type:"POST",url:site_url1+"meetings/acceptInvitation",data:{id:a,roomName:b}}).done(function(b){$("#meetingaction_"+a).hide()})}function rejectMeetingInvitaion(a){$.ajax({type:"POST",url:site_url1+"meetings/rejectInvitation",data:{id:a}}).done(function(b){$("#meeting_"+a).hide()})}
function detailMeeting(a){$("#below_meeting_detail_"+a).toggle()}
function planMetting(){$(".friends_list").hide();$(".upper-area").hide();$("#activeChatTab").hide();$(".meeting-panel").toggle();$(".meeting-panel").is(":visible")?($("#meet-active").show(),$("#meet-lazy").hide(),$("#notf-active").hide(),$("#notf-lazy").show(),$("#jact-active").hide(),$("#jact-lazy").show(),$("#tab-msg").html("<h3>Plan Meeting</h3>")):($("#meet-active").hide(),$("#meet-lazy").show(),$(".friends_list").show(),$("#tab-msg").html("<h3>Who is Online</h3>"))}
function getMeetingRequestsCount(){$.ajax({type:"POST",url:site_url1+"meetings/getMeetingRequestsCount",data:{}}).done(function(a){var b=JSON.parse(a);a=b.count;b=b.showAlert;newMeetGbValue=a;updatedGbValue=newPendGbValue+newReqGbValue+newNotfGbValue+newMeetGbValue;0!=updatedGbValue?($("#globalNotify").show(),$("#globalNotify").html(updatedGbValue)):$("#globalNotify").hide();"0"==a?$("#chat_meetings_count").hide():($("#chat_meetings_count").show(),$("#chat_meetings_count").html(a));1==b&&$.msgBox({title:"Alert",
content:"New Meeting Notification"})})}
function leaveMeetingRoom(a){var b=$("#chatarea").children(".chatarea-inner:visible").length;if(5>b)var c=215*(b-1);$("#chatarea",window.parent.document).css("min-width",c+"px");$(".right-area",window.parent.document).css("min-width",c+"px");$("#li_"+a,window.parent.document).remove();$("#par_"+a,window.parent.document).hide();b=$("#chatarea",window.parent.document).children(".chatarea-inner:visible").length;1==b&&($("#chatarea",window.parent.document).children(".chatarea-inner").addClass("one-inner"),$("#chatarea",
window.parent.document).addClass("chatarea-wrapper-main"));0==b&&$(".right-area",window.parent.document).hide();b=parent.roomArray.indexOf(a);-1<b&&parent.roomArray.splice(b,1);$.ajax({type:"POST",url:site_url1+"meetings/leaveRoom",data:{roomName:a}}).done(function(b){"true"==b&&$("#chatwindow"+a,window.parent.document).hide()});$("#joinmetting_"+a,window.parent.document).show()};
