var Base64=function(){return{encode:function(r){var q="",s,l,t,c,a,b,d=0;do s=r.charCodeAt(d++),l=r.charCodeAt(d++),t=r.charCodeAt(d++),c=s>>2,s=(s&3)<<4|l>>4,a=(l&15)<<2|t>>6,b=t&63,isNaN(l)?a=b=64:isNaN(t)&&(b=64),q=q+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(s)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b);
while(d<r.length);return q},decode:function(r){var q="",s,l,t,c,a,b=0;r=r.replace(/[^A-Za-z0-9\+\/\=]/g,"");do s="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(r.charAt(b++)),l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(r.charAt(b++)),c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(r.charAt(b++)),a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(r.charAt(b++)),s=s<<2|l>>4,l=(l&15)<<
4|c>>2,t=(c&3)<<6|a,q+=String.fromCharCode(s),64!=c&&(q+=String.fromCharCode(l)),64!=a&&(q+=String.fromCharCode(t));while(b<r.length);return q}}}(),MD5=function(){var r=function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535},q=function(a){for(var b=[],c=0;c<8*a.length;c+=8)b[c>>5]|=(a.charCodeAt(c/8)&255)<<c%32;return b},s=function(a){for(var b="",c=0;c<32*a.length;c+=8)b+=String.fromCharCode(a[c>>5]>>>c%32&255);return b},l=function(a){for(var b="",c=0;c<4*a.length;c++)b+=
"0123456789abcdef".charAt(a[c>>2]>>c%4*8+4&15)+"0123456789abcdef".charAt(a[c>>2]>>c%4*8&15);return b},t=function(a){for(var b="",c,d,e=0;e<4*a.length;e+=3)for(c=(a[e>>2]>>e%4*8&255)<<16|(a[e+1>>2]>>(e+1)%4*8&255)<<8|a[e+2>>2]>>(e+2)%4*8&255,d=0;4>d;d++)b=8*e+6*d>32*a.length?b+"":b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>6*(3-d)&63);return b},c=function(a,b,c,d,e,f){a=r(r(b,a),r(d,f));return r(a<<e|a>>>32-e,c)},a=function(a,b,d,h,e,f,m){return c(b&d|~b&h,a,b,e,
f,m)},b=function(a,b,d,h,e,f,m){return c(b&h|d&~h,a,b,e,f,m)},d=function(a,b,d,h,e,f,m){return c(d^(b|~h),a,b,e,f,m)},m=function(g,m){g[m>>5]|=128<<m%32;g[(m+64>>>9<<4)+14]=m;for(var k=1732584193,h=-271733879,e=-1732584194,f=271733878,p,l,q,s,n=0;n<g.length;n+=16)p=k,l=h,q=e,s=f,k=a(k,h,e,f,g[n+0],7,-680876936),f=a(f,k,h,e,g[n+1],12,-389564586),e=a(e,f,k,h,g[n+2],17,606105819),h=a(h,e,f,k,g[n+3],22,-1044525330),k=a(k,h,e,f,g[n+4],7,-176418897),f=a(f,k,h,e,g[n+5],12,1200080426),e=a(e,f,k,h,g[n+6],
17,-1473231341),h=a(h,e,f,k,g[n+7],22,-45705983),k=a(k,h,e,f,g[n+8],7,1770035416),f=a(f,k,h,e,g[n+9],12,-1958414417),e=a(e,f,k,h,g[n+10],17,-42063),h=a(h,e,f,k,g[n+11],22,-1990404162),k=a(k,h,e,f,g[n+12],7,1804603682),f=a(f,k,h,e,g[n+13],12,-40341101),e=a(e,f,k,h,g[n+14],17,-1502002290),h=a(h,e,f,k,g[n+15],22,1236535329),k=b(k,h,e,f,g[n+1],5,-165796510),f=b(f,k,h,e,g[n+6],9,-1069501632),e=b(e,f,k,h,g[n+11],14,643717713),h=b(h,e,f,k,g[n+0],20,-373897302),k=b(k,h,e,f,g[n+5],5,-701558691),f=b(f,k,h,
e,g[n+10],9,38016083),e=b(e,f,k,h,g[n+15],14,-660478335),h=b(h,e,f,k,g[n+4],20,-405537848),k=b(k,h,e,f,g[n+9],5,568446438),f=b(f,k,h,e,g[n+14],9,-1019803690),e=b(e,f,k,h,g[n+3],14,-187363961),h=b(h,e,f,k,g[n+8],20,1163531501),k=b(k,h,e,f,g[n+13],5,-1444681467),f=b(f,k,h,e,g[n+2],9,-51403784),e=b(e,f,k,h,g[n+7],14,1735328473),h=b(h,e,f,k,g[n+12],20,-1926607734),k=c(h^e^f,k,h,g[n+5],4,-378558),f=c(k^h^e,f,k,g[n+8],11,-2022574463),e=c(f^k^h,e,f,g[n+11],16,1839030562),h=c(e^f^k,h,e,g[n+14],23,-35309556),
k=c(h^e^f,k,h,g[n+1],4,-1530992060),f=c(k^h^e,f,k,g[n+4],11,1272893353),e=c(f^k^h,e,f,g[n+7],16,-155497632),h=c(e^f^k,h,e,g[n+10],23,-1094730640),k=c(h^e^f,k,h,g[n+13],4,681279174),f=c(k^h^e,f,k,g[n+0],11,-358537222),e=c(f^k^h,e,f,g[n+3],16,-722521979),h=c(e^f^k,h,e,g[n+6],23,76029189),k=c(h^e^f,k,h,g[n+9],4,-640364487),f=c(k^h^e,f,k,g[n+12],11,-421815835),e=c(f^k^h,e,f,g[n+15],16,530742520),h=c(e^f^k,h,e,g[n+2],23,-995338651),k=d(k,h,e,f,g[n+0],6,-198630844),f=d(f,k,h,e,g[n+7],10,1126891415),e=d(e,
f,k,h,g[n+14],15,-1416354905),h=d(h,e,f,k,g[n+5],21,-57434055),k=d(k,h,e,f,g[n+12],6,1700485571),f=d(f,k,h,e,g[n+3],10,-1894986606),e=d(e,f,k,h,g[n+10],15,-1051523),h=d(h,e,f,k,g[n+1],21,-2054922799),k=d(k,h,e,f,g[n+8],6,1873313359),f=d(f,k,h,e,g[n+15],10,-30611744),e=d(e,f,k,h,g[n+6],15,-1560198380),h=d(h,e,f,k,g[n+13],21,1309151649),k=d(k,h,e,f,g[n+4],6,-145523070),f=d(f,k,h,e,g[n+11],10,-1120210379),e=d(e,f,k,h,g[n+2],15,718787259),h=d(h,e,f,k,g[n+9],21,-343485551),k=r(k,p),h=r(h,l),e=r(e,q),f=
r(f,s);return[k,h,e,f]},p=function(a,b){var c=q(a);16<c.length&&(c=m(c,8*a.length));for(var d=Array(16),e=Array(16),f=0;16>f;f++)d[f]=c[f]^909522486,e[f]=c[f]^1549556828;c=m(d.concat(q(b)),512+8*b.length);return m(e.concat(c),640)};return{hexdigest:function(a){return l(m(q(a),8*a.length))},b64digest:function(a){return t(m(q(a),8*a.length))},hash:function(a){return s(m(q(a),8*a.length))},hmac_hexdigest:function(a,b){return l(p(a,b))},hmac_b64digest:function(a,b){return t(p(a,b))},hmac_hash:function(a,
b){return s(p(a,b))},test:function(){return"900150983cd24fb0d6963f7d28e17f72"===MD5.hexdigest("abc")}}}();Function.prototype.bind||(Function.prototype.bind=function(r){var q=this;return function(){return q.apply(r,arguments)}});Function.prototype.prependArg||(Function.prototype.prependArg=function(r){var q=this;return function(){for(var s=[r],l=0;l<arguments.length;l++)s.push(arguments[l]);return q.apply(this,s)}});
Array.prototype.indexOf||(Array.prototype.indexOf=function(r,q){var s=this.length,l=Number(q)||0,l=0>l?Math.ceil(l):Math.floor(l);for(0>l&&(l+=s);l<s;l++)if(l in this&&this[l]===r)return l;return-1});
(function(r){function q(a,b){return new c.Builder(a,b)}function s(a){return new c.Builder("message",a)}function l(a){return new c.Builder("iq",a)}function t(a){return new c.Builder("presence",a)}var c;c={VERSION:"1.0.1",NS:{HTTPBIND:"http://jabber.org/protocol/httpbind",BOSH:"urn:xmpp:xbosh",CLIENT:"jabber:client",AUTH:"jabber:iq:auth",ROSTER:"jabber:iq:roster",PROFILE:"jabber:iq:profile",DISCO_INFO:"http://jabber.org/protocol/disco#info",DISCO_ITEMS:"http://jabber.org/protocol/disco#items",MUC:"http://jabber.org/protocol/muc",
SASL:"urn:ietf:params:xml:ns:xmpp-sasl",STREAM:"http://etherx.jabber.org/streams",BIND:"urn:ietf:params:xml:ns:xmpp-bind",SESSION:"urn:ietf:params:xml:ns:xmpp-session",VERSION:"jabber:iq:version",STANZAS:"urn:ietf:params:xml:ns:xmpp-stanzas"},addNamespace:function(a,b){c.NS[a]=b},Status:{ERROR:0,CONNECTING:1,CONNFAIL:2,AUTHENTICATING:3,AUTHFAIL:4,CONNECTED:5,DISCONNECTED:6,DISCONNECTING:7,ATTACHED:8},LogLevel:{DEBUG:0,INFO:1,WARN:2,ERROR:3,FATAL:4},ElementType:{NORMAL:1,TEXT:3},TIMEOUT:1.1,SECONDARY_TIMEOUT:0.1,
forEachChild:function(a,b,d){var m,p;for(m=0;m<a.childNodes.length;m++)p=a.childNodes[m],p.nodeType!=c.ElementType.NORMAL||b&&!this.isTagEqual(p,b)||d(p)},isTagEqual:function(a,b){return a.tagName.toLowerCase()==b.toLowerCase()},_xmlGenerator:null,_makeGenerator:function(){var a;window.ActiveXObject?(a=new ActiveXObject("Microsoft.XMLDOM"),a.appendChild(a.createElement("strophe"))):a=document.implementation.createDocument("jabber:client","strophe",null);return a},xmlElement:function(a){if(!a)return null;
var b=null;c._xmlGenerator||(c._xmlGenerator=c._makeGenerator());var b=c._xmlGenerator.createElement(a),d,m,p;for(d=1;d<arguments.length;d++)if(arguments[d])if("string"==typeof arguments[d]||"number"==typeof arguments[d])b.appendChild(c.xmlTextNode(arguments[d]));else if("object"==typeof arguments[d]&&"function"==typeof arguments[d].sort)for(m=0;m<arguments[d].length;m++)"object"==typeof arguments[d][m]&&"function"==typeof arguments[d][m].sort&&b.setAttribute(arguments[d][m][0],arguments[d][m][1]);
else if("object"==typeof arguments[d])for(p in arguments[d])arguments[d].hasOwnProperty(p)&&b.setAttribute(p,arguments[d][p]);return b},xmlescape:function(a){a=a.replace(/\&/g,"&amp;");a=a.replace(/</g,"&lt;");return a=a.replace(/>/g,"&gt;")},xmlTextNode:function(a){a=c.xmlescape(a);c._xmlGenerator||(c._xmlGenerator=c._makeGenerator());return c._xmlGenerator.createTextNode(a)},getText:function(a){if(!a)return null;var b="";0===a.childNodes.length&&a.nodeType==c.ElementType.TEXT&&(b+=a.nodeValue);
for(var d=0;d<a.childNodes.length;d++)a.childNodes[d].nodeType==c.ElementType.TEXT&&(b+=a.childNodes[d].nodeValue);return b},copyElement:function(a){var b,d;if(a.nodeType==c.ElementType.NORMAL){d=c.xmlElement(a.tagName);for(b=0;b<a.attributes.length;b++)d.setAttribute(a.attributes[b].nodeName.toLowerCase(),a.attributes[b].value);for(b=0;b<a.childNodes.length;b++)d.appendChild(c.copyElement(a.childNodes[b]))}else a.nodeType==c.ElementType.TEXT&&(d=c.xmlTextNode(a.nodeValue));return d},escapeNode:function(a){return a.replace(/^\s+|\s+$/g,
"").replace(/\\/g,"\\5c").replace(/ /g,"\\20").replace(/\"/g,"\\22").replace(/\&/g,"\\26").replace(/\'/g,"\\27").replace(/\//g,"\\2f").replace(/:/g,"\\3a").replace(/</g,"\\3c").replace(/>/g,"\\3e").replace(/@/g,"\\40")},unescapeNode:function(a){return a.replace(/\\20/g," ").replace(/\\22/g,'"').replace(/\\26/g,"&").replace(/\\27/g,"'").replace(/\\2f/g,"/").replace(/\\3a/g,":").replace(/\\3c/g,"<").replace(/\\3e/g,">").replace(/\\40/g,"@").replace(/\\5c/g,"\\")},getNodeFromJid:function(a){return 0>
a.indexOf("@")?null:a.split("@")[0]},getDomainFromJid:function(a){a=c.getBareJidFromJid(a);if(0>a.indexOf("@"))return a;a=a.split("@");a.splice(0,1);return a.join("@")},getResourceFromJid:function(a){a=a.split("/");if(2>a.length)return null;a.splice(0,1);return a.join("/")},getBareJidFromJid:function(a){return a.split("/")[0]},log:function(a,b){},debug:function(a){this.log(this.LogLevel.DEBUG,a)},info:function(a){this.log(this.LogLevel.INFO,a)},warn:function(a){this.log(this.LogLevel.WARN,a)},error:function(a){this.log(this.LogLevel.ERROR,
a)},fatal:function(a){this.log(this.LogLevel.FATAL,a)},serialize:function(a){var b;if(!a)return null;"function"===typeof a.tree&&(a=a.tree());var d=a.nodeName,m,p;a.getAttribute("_realname")&&(d=a.getAttribute("_realname"));b="<"+d;for(m=0;m<a.attributes.length;m++)"_realname"!=a.attributes[m].nodeName&&(b+=" "+a.attributes[m].nodeName.toLowerCase()+"='"+a.attributes[m].value.replace("&","&amp;").replace("'","&apos;").replace("<","&lt;")+"'");if(0<a.childNodes.length){b+=">";for(m=0;m<a.childNodes.length;m++)p=
a.childNodes[m],p.nodeType==c.ElementType.NORMAL?b+=c.serialize(p):p.nodeType==c.ElementType.TEXT&&(b+=p.nodeValue);b+="</"+d+">"}else b+="/>";return b},_requestId:0,_connectionPlugins:{},addConnectionPlugin:function(a,b){c._connectionPlugins[a]=b},Builder:function(a,b){if("presence"==a||"message"==a||"iq"==a)b&&!b.xmlns?b.xmlns=c.NS.CLIENT:b||(b={xmlns:c.NS.CLIENT});this.node=this.nodeTree=c.xmlElement(a,b)}};c.Builder.prototype={tree:function(){return this.nodeTree},toString:function(){return c.serialize(this.nodeTree)},
up:function(){this.node=this.node.parentNode;return this},attrs:function(a){for(var b in a)a.hasOwnProperty(b)&&this.node.setAttribute(b,a[b]);return this},c:function(a,b){var d=c.xmlElement(a,b);this.node.appendChild(d);this.node=d;return this},cnode:function(a){this.node.appendChild(a);this.node=a;return this},t:function(a){a=c.xmlTextNode(a);this.node.appendChild(a);return this}};c.Handler=function(a,b,d,m,p,g,l){this.handler=a;this.ns=b;this.name=d;this.type=m;this.id=p;this.options=l||{matchbare:!1};
this.options.matchBare||(this.options.matchBare=!1);this.from=this.options.matchBare?c.getBareJidFromJid(g):g;this.user=!0};c.Handler.prototype={isMatch:function(a){var b,d=null,d=this.options.matchBare?c.getBareJidFromJid(a.getAttribute("from")):a.getAttribute("from");b=!1;if(this.ns){var m=this;c.forEachChild(a,null,function(a){a.getAttribute("xmlns")==m.ns&&(b=!0)});b=b||a.getAttribute("xmlns")==this.ns}else b=!0;return!b||this.name&&!c.isTagEqual(a,this.name)||this.type&&a.getAttribute("type")!==
this.type||this.id&&a.getAttribute("id")!==this.id||this.from&&d!==this.from?!1:!0},run:function(a){var b=null;try{b=this.handler(a)}catch(d){throw d.sourceURL?c.fatal("error: "+this.handler+" "+d.sourceURL+":"+d.line+" - "+d.name+": "+d.message):d.fileName?("undefined"!=typeof console&&(console.trace(),console.error(this.handler," - error - ",d,d.message)),c.fatal("error: "+this.handler+" "+d.fileName+":"+d.lineNumber+" - "+d.name+": "+d.message)):c.fatal("error: "+this.handler),d;}return b},toString:function(){return"{Handler: "+
this.handler+"("+this.name+","+this.id+","+this.ns+")}"}};c.TimedHandler=function(a,b){this.period=a;this.handler=b;this.lastCalled=(new Date).getTime();this.user=!0};c.TimedHandler.prototype={run:function(){this.lastCalled=(new Date).getTime();return this.handler()},reset:function(){this.lastCalled=(new Date).getTime()},toString:function(){return"{TimedHandler: "+this.handler+"("+this.period+")}"}};c.Request=function(a,b,d,m){this.id=++c._requestId;this.xmlData=a;this.data=c.serialize(a);this.func=
this.origFunc=b;this.rid=d;this.date=NaN;this.sends=m||0;this.abort=!1;this.dead=null;this.age=function(){return this.date?(new Date-this.date)/1E3:0};this.timeDead=function(){return this.dead?(new Date-this.dead)/1E3:0};this.xhr=this._newXHR()};c.Request.prototype={getResponse:function(){var a=null;if(this.xhr.responseXML&&this.xhr.responseXML.documentElement){if(a=this.xhr.responseXML.documentElement,"parsererror"==a.tagName)throw c.error("invalid response received"),c.error("responseText: "+this.xhr.responseText),
c.error("responseXML: "+c.serialize(this.xhr.responseXML)),"parsererror";}else this.xhr.responseText&&(c.error("invalid response received"),c.error("responseText: "+this.xhr.responseText),c.error("responseXML: "+c.serialize(this.xhr.responseXML)));return a},_newXHR:function(){var a=null;window.XMLHttpRequest?(a=new XMLHttpRequest,a.overrideMimeType&&a.overrideMimeType("text/xml")):window.ActiveXObject&&(a=new ActiveXObject("Microsoft.XMLHTTP"));a.onreadystatechange=this.func.prependArg(this);return a}};
c.Connection=function(a){this.service=a;this.jid="";this.rid=Math.floor(4294967295*Math.random());this.streamId=this.sid=null;this.do_bind=this.do_session=!1;this.timedHandlers=[];this.handlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this._disconnectTimeout=this._idleTimeout=null;this.connected=this.disconnecting=this.authenticated=!1;this.errors=0;this.paused=!1;this.hold=1;this.wait=60;this.window=5;this._data=[];this._requests=[];this._uniqueId=Math.round(1E4*
Math.random());this._sasl_challenge_handler=this._sasl_failure_handler=this._sasl_success_handler=null;this._idleTimeout=setTimeout(this._onIdle.bind(this),100);for(var b in c._connectionPlugins)c._connectionPlugins.hasOwnProperty(b)&&(a=function(){},a.prototype=c._connectionPlugins[b],this[b]=new a,this[b].init(this))};c.Connection.prototype={reset:function(){this.rid=Math.floor(4294967295*Math.random());this.streamId=this.sid=null;this.do_bind=this.do_session=!1;this.timedHandlers=[];this.handlers=
[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this.connected=this.disconnecting=this.authenticated=!1;this.errors=0;this._requests=[];this._uniqueId=Math.round(1E4*Math.random())},pause:function(){this.paused=!0},resume:function(){this.paused=!1},getUniqueId:function(a){return"string"==typeof a||"number"==typeof a?++this._uniqueId+":"+a:++this._uniqueId+""},connect:function(a,b,d,m,p){this.jid=a;this.pass=b;this.connect_callback=d;this.authenticated=this.connected=
this.disconnecting=!1;this.errors=0;this.wait=m||this.wait;this.hold=p||this.hold;this.domain=c.getDomainFromJid(this.jid);a=this._buildBody().attrs({to:this.domain,"xml:lang":"en",wait:this.wait,hold:this.hold,content:"text/xml; charset=utf-8",ver:"1.6","xmpp:version":"1.0","xmlns:xmpp":c.NS.BOSH});this._changeConnectStatus(c.Status.CONNECTING,null);this._requests.push(new c.Request(a.tree(),this._onRequestStateChange.bind(this).prependArg(this._connect_cb.bind(this)),a.tree().getAttribute("rid")));
this._throttledRequestHandler()},attach:function(a,b,d,m,p,g,l){this.jid=a;this.sid=b;this.rid=d;this.connect_callback=m;this.domain=c.getDomainFromJid(this.jid);this.connected=this.authenticated=!0;this.wait=p||this.wait;this.hold=g||this.hold;this.window=l||this.window;this._changeConnectStatus(c.Status.ATTACHED,null)},xmlInput:function(a){},xmlOutput:function(a){},rawInput:function(a){},rawOutput:function(a){},send:function(a){if(null!==a){if("function"===typeof a.sort)for(var b=0;b<a.length;b++)this._queueData(a[b]);
else"function"===typeof a.tree?this._queueData(a.tree()):this._queueData(a);this._throttledRequestHandler();clearTimeout(this._idleTimeout);this._idleTimeout=setTimeout(this._onIdle.bind(this),100)}},flush:function(){clearTimeout(this._idleTimeout);this._onIdle()},sendIQ:function(a,b,c,m){var p=null,g=this;"function"===typeof a.tree&&(a=a.tree());var l=a.getAttribute("id");l||(l=this.getUniqueId("sendIQ"),a.setAttribute("id",l));var k=this.addHandler(function(a){p&&g.deleteTimedHandler(p);var e=a.getAttribute("type");
if("result"===e)b&&b(a);else if("error"===e)c&&c(a);else throw{name:"StropheError",message:"Got bad IQ type of "+e};},null,"iq",null,l);m&&(p=this.addTimedHandler(m,function(){g.deleteHandler(k);c&&c(null);return!1}));this.send(a);return l},_queueData:function(a){if(null===a||!a.tagName||!a.childNodes)throw{name:"StropheError",message:"Cannot queue non-DOMElement."};this._data.push(a)},_sendRestart:function(){this._data.push("restart");this._throttledRequestHandler();clearTimeout(this._idleTimeout);
this._idleTimeout=setTimeout(this._onIdle.bind(this),100)},addTimedHandler:function(a,b){var d=new c.TimedHandler(a,b);this.addTimeds.push(d);return d},deleteTimedHandler:function(a){this.removeTimeds.push(a)},addHandler:function(a,b,d,m,p,g,l){a=new c.Handler(a,b,d,m,p,g,l);this.addHandlers.push(a);return a},deleteHandler:function(a){this.removeHandlers.push(a)},disconnect:function(a){this._changeConnectStatus(c.Status.DISCONNECTING,a);c.info("Disconnect was called because: "+a);this.connected&&
(this._disconnectTimeout=this._addSysTimedHandler(3E3,this._onDisconnectTimeout.bind(this)),this._sendTerminate())},_changeConnectStatus:function(a,b){for(var d in c._connectionPlugins)if(c._connectionPlugins.hasOwnProperty(d)){var m=this[d];if(m.statusChanged)try{m.statusChanged(a,b)}catch(p){c.error(""+d+" plugin caused an exception changing status: "+p)}}if(this.connect_callback)try{this.connect_callback(a,b)}catch(g){c.error("User connection callback caused an exception: "+g)}},_buildBody:function(){var a=
q("body",{rid:this.rid++,xmlns:c.NS.HTTPBIND});null!==this.sid&&a.attrs({sid:this.sid});return a},_removeRequest:function(a){c.debug("removing request");var b;for(b=this._requests.length-1;0<=b;b--)a==this._requests[b]&&this._requests.splice(b,1);a.xhr.onreadystatechange=function(){};this._throttledRequestHandler()},_restartRequest:function(a){var b=this._requests[a];null===b.dead&&(b.dead=new Date);this._processRequest(a)},_processRequest:function(a){var b=this._requests[a],d=-1;try{4==b.xhr.readyState&&
(d=b.xhr.status)}catch(m){c.error("caught an error in _requests["+a+"], reqStatus: "+d)}"undefined"==typeof d&&(d=-1);var p=b.age(),p=!isNaN(p)&&p>Math.floor(c.TIMEOUT*this.wait),g=null!==b.dead&&b.timeDead()>Math.floor(c.SECONDARY_TIMEOUT*this.wait),d=4==b.xhr.readyState&&(1>d||500<=d);if(p||g||d)g&&c.error("Request "+this._requests[a].id+" timed out (secondary), restarting"),b.abort=!0,b.xhr.abort(),b.xhr.onreadystatechange=function(){},this._requests[a]=new c.Request(b.xmlData,b.origFunc,b.rid,
b.sends),b=this._requests[a];if(0===b.xhr.readyState){c.debug("request id "+b.id+"."+b.sends+" posting");b.date=new Date;try{b.xhr.open("POST",this.service,!0)}catch(l){c.error("XHR open failed.");this.connected||this._changeConnectStatus(c.Status.CONNFAIL,"bad-service");this.disconnect();return}a=function(){b.xhr.send(b.data)};1<b.sends?(d=1E3*Math.pow(b.sends,3),setTimeout(a,d)):a();b.sends++;this.xmlOutput(b.xmlData);this.rawOutput(b.data)}else c.debug("_processRequest: "+(0===a?"first":"second")+
" request has readyState of "+b.xhr.readyState)},_throttledRequestHandler:function(){this._requests?c.debug("_throttledRequestHandler called with "+this._requests.length+" requests"):c.debug("_throttledRequestHandler called with undefined requests");this._requests&&0!==this._requests.length&&(0<this._requests.length&&this._processRequest(0),1<this._requests.length&&Math.abs(this._requests[0].rid-this._requests[1].rid)<this.window-1&&this._processRequest(1))},_onRequestStateChange:function(a,b){c.debug("request id "+
b.id+"."+b.sends+" state changed to "+b.xhr.readyState);if(b.abort)b.abort=!1;else{var d;if(4==b.xhr.readyState){d=0;try{d=b.xhr.status}catch(m){}"undefined"==typeof d&&(d=0);if(this.disconnecting&&400<=d)this._hitError(d);else{var p=this._requests[0]==b,g=this._requests[1]==b;if(0<d&&500>d||5<b.sends)this._removeRequest(b),c.debug("request id "+b.id+" should now be removed");if(200==d)(g||p&&0<this._requests.length&&this._requests[0].age()>Math.floor(c.SECONDARY_TIMEOUT*this.wait))&&this._restartRequest(0),
c.debug("request id "+b.id+"."+b.sends+" got 200"),a(b),this.errors=0;else if(c.error("request id "+b.id+"."+b.sends+" error "+d+" happened"),0===d||400<=d&&600>d||12E3<=d)this._hitError(d),400<=d&&500>d&&(this._changeConnectStatus(c.Status.DISCONNECTING,null),this._doDisconnect());0<d&&1E4>d||5<b.sends||this._throttledRequestHandler()}}}},_hitError:function(a){this.errors++;c.warn("request errored, status: "+a+", number of errors: "+this.errors);4<this.errors&&this._onDisconnectTimeout()},_doDisconnect:function(){c.info("_doDisconnect was called");
this.disconnecting=this.authenticated=!1;this.streamId=this.sid=null;this.rid=Math.floor(4294967295*Math.random());this.connected&&(this._changeConnectStatus(c.Status.DISCONNECTED,null),this.connected=!1);this.handlers=[];this.timedHandlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[]},_dataRecv:function(a){try{var b=a.getResponse()}catch(d){if("parsererror"!=d)throw d;this.disconnect("strophe-parsererror")}if(null!==b){this.xmlInput(b);for(this.rawInput(c.serialize(b));0<
this.removeHandlers.length;)a=this.removeHandlers.pop(),a=this.handlers.indexOf(a),0<=a&&this.handlers.splice(a,1);for(;0<this.addHandlers.length;)this.handlers.push(this.addHandlers.pop());if(this.disconnecting&&0===this._requests.length)this.deleteTimedHandler(this._disconnectTimeout),this._disconnectTimeout=null,this._doDisconnect();else if(a=b.getAttribute("type"),null!==a&&"terminate"==a)a=b.getAttribute("condition"),b=b.getElementsByTagName("conflict"),null!==a?("remote-stream-error"==a&&0<
b.length&&(a="conflict"),this._changeConnectStatus(c.Status.CONNFAIL,a)):this._changeConnectStatus(c.Status.CONNFAIL,"unknown"),this.disconnect();else{var m=this;c.forEachChild(b,null,function(a){var b,c;c=m.handlers;m.handlers=[];for(b=0;b<c.length;b++){var d=c[b];!d.isMatch(a)||!m.authenticated&&d.user?m.handlers.push(d):d.run(a)&&m.handlers.push(d)}})}}},_sendTerminate:function(){c.info("_sendTerminate was called");var a=this._buildBody().attrs({type:"terminate"});this.authenticated&&a.c("presence",
{xmlns:c.NS.CLIENT,type:"unavailable"});this.disconnecting=!0;a=new c.Request(a.tree(),this._onRequestStateChange.bind(this).prependArg(this._dataRecv.bind(this)),a.tree().getAttribute("rid"));this._requests.push(a);this._throttledRequestHandler()},_connect_cb:function(a){c.info("_connect_cb was called");this.connected=!0;if(a=a.getResponse()){this.xmlInput(a);this.rawInput(c.serialize(a));var b=a.getAttribute("type");if(null!==b&&"terminate"==b)b=a.getAttribute("condition"),a=a.getElementsByTagName("conflict"),
null!==b?("remote-stream-error"==b&&0<a.length&&(b="conflict"),this._changeConnectStatus(c.Status.CONNFAIL,b)):this._changeConnectStatus(c.Status.CONNFAIL,"unknown");else{this.sid||(this.sid=a.getAttribute("sid"));this.stream_id||(this.stream_id=a.getAttribute("authid"));if(b=a.getAttribute("requests"))this.window=parseInt(b,10);if(b=a.getAttribute("hold"))this.hold=parseInt(b,10);if(b=a.getAttribute("wait"))this.wait=parseInt(b,10);var d=b=!1,m=!1;a=a.getElementsByTagName("mechanism");var p,g;if(0<
a.length){for(p=0;p<a.length;p++)g=c.getText(a[p]),"DIGEST-MD5"==g?d=!0:"PLAIN"==g?b=!0:"ANONYMOUS"==g&&(m=!0);null===c.getNodeFromJid(this.jid)&&m?(this._changeConnectStatus(c.Status.AUTHENTICATING,null),this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null),this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null),this.send(q("auth",{xmlns:c.NS.SASL,mechanism:"ANONYMOUS"}).tree())):null===c.getNodeFromJid(this.jid)?
(this._changeConnectStatus(c.Status.CONNFAIL,"x-strophe-bad-non-anon-jid"),this.disconnect()):d?(this._changeConnectStatus(c.Status.AUTHENTICATING,null),this._sasl_challenge_handler=this._addSysHandler(this._sasl_challenge1_cb.bind(this),null,"challenge",null,null),this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null),this.send(q("auth",{xmlns:c.NS.SASL,mechanism:"DIGEST-MD5"}).tree())):b?(a=c.getBareJidFromJid(this.jid),a=a+"\x00"+c.getNodeFromJid(this.jid),
a+="\x00",a+=this.pass,this._changeConnectStatus(c.Status.AUTHENTICATING,null),this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null),this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null),a=Base64.encode(a),this.send(q("auth",{xmlns:c.NS.SASL,mechanism:"PLAIN"}).t(a).tree())):(this._changeConnectStatus(c.Status.AUTHENTICATING,null),this._addSysHandler(this._auth1_cb.bind(this),null,null,null,"_auth_1"),
this.send(l({type:"get",to:this.domain,id:"_auth_1"}).c("query",{xmlns:c.NS.AUTH}).c("username",{}).t(c.getNodeFromJid(this.jid)).tree()))}else a=this._buildBody(),this._requests.push(new c.Request(a.tree(),this._onRequestStateChange.bind(this).prependArg(this._connect_cb.bind(this)),a.tree().getAttribute("rid"))),this._throttledRequestHandler()}}},_sasl_challenge1_cb:function(a){var b=/([a-z]+)=("[^"]+"|[^,"]+)(?:,|$)/,d=Base64.decode(c.getText(a));a=MD5.hexdigest(1234567890*Math.random());var m=
"",p=null,g="",l;for(this.deleteHandler(this._sasl_failure_handler);d.match(b);)switch(l=d.match(b),d=d.replace(l[0],""),l[2]=l[2].replace(/^"(.+)"$/,"$1"),l[1]){case "realm":m=l[2];break;case "nonce":g=l[2];break;case "host":p=l[2]}b="xmpp/"+this.domain;null!==p&&(b=b+"/"+p);p=MD5.hash(c.getNodeFromJid(this.jid)+":"+m+":"+this.pass)+":"+g+":"+a;d="AUTHENTICATE:"+b;l=""+("username="+this._quote(c.getNodeFromJid(this.jid))+",");l+="realm="+this._quote(m)+",";l+="nonce="+this._quote(g)+",";l+="cnonce="+
this._quote(a)+",";l+='nc="00000001",qop="auth",';l+="digest-uri="+this._quote(b)+",";l+="response="+this._quote(MD5.hexdigest(MD5.hexdigest(p)+":"+g+":00000001:"+a+":auth:"+MD5.hexdigest(d)))+",";l+='charset="utf-8"';this._sasl_challenge_handler=this._addSysHandler(this._sasl_challenge2_cb.bind(this),null,"challenge",null,null);this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),
null,"failure",null,null);this.send(q("response",{xmlns:c.NS.SASL}).t(Base64.encode(l)).tree());return!1},_quote:function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"'},_sasl_challenge2_cb:function(a){this.deleteHandler(this._sasl_success_handler);this.deleteHandler(this._sasl_failure_handler);this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,
"failure",null,null);this.send(q("response",{xmlns:c.NS.SASL}).tree());return!1},_auth1_cb:function(a){a=l({type:"set",id:"_auth_2"}).c("query",{xmlns:c.NS.AUTH}).c("username",{}).t(c.getNodeFromJid(this.jid)).up().c("password").t(this.pass);c.getResourceFromJid(this.jid)||(this.jid=c.getBareJidFromJid(this.jid)+"/strophe");a.up().c("resource",{}).t(c.getResourceFromJid(this.jid));this._addSysHandler(this._auth2_cb.bind(this),null,null,null,"_auth_2");this.send(a.tree());return!1},_sasl_success_cb:function(a){c.info("SASL authentication succeeded.");
this.deleteHandler(this._sasl_failure_handler);this._sasl_failure_handler=null;this._sasl_challenge_handler&&(this.deleteHandler(this._sasl_challenge_handler),this._sasl_challenge_handler=null);this._addSysHandler(this._sasl_auth1_cb.bind(this),null,"stream:features",null,null);this._sendRestart();return!1},_sasl_auth1_cb:function(a){var b,d;for(b=0;b<a.childNodes.length;b++)d=a.childNodes[b],"bind"==d.nodeName&&(this.do_bind=!0),"session"==d.nodeName&&(this.do_session=!0);this.do_bind?(this._addSysHandler(this._sasl_bind_cb.bind(this),
null,null,null,"_bind_auth_2"),(a=c.getResourceFromJid(this.jid))?this.send(l({type:"set",id:"_bind_auth_2"}).c("bind",{xmlns:c.NS.BIND}).c("resource",{}).t(a).tree()):this.send(l({type:"set",id:"_bind_auth_2"}).c("bind",{xmlns:c.NS.BIND}).tree())):this._changeConnectStatus(c.Status.AUTHFAIL,null);return!1},_sasl_bind_cb:function(a){if("error"==a.getAttribute("type"))return c.info("SASL binding failed."),this._changeConnectStatus(c.Status.AUTHFAIL,null),!1;a=a.getElementsByTagName("bind");if(0<a.length)a=
a[0].getElementsByTagName("jid"),0<a.length&&(this.jid=c.getText(a[0]),this.do_session?(this._addSysHandler(this._sasl_session_cb.bind(this),null,null,null,"_session_auth_2"),this.send(l({type:"set",id:"_session_auth_2"}).c("session",{xmlns:c.NS.SESSION}).tree())):(this.authenticated=!0,this._changeConnectStatus(c.Status.CONNECTED,null)));else return c.info("SASL binding failed."),this._changeConnectStatus(c.Status.AUTHFAIL,null),!1},_sasl_session_cb:function(a){"result"==a.getAttribute("type")?(this.authenticated=
!0,this._changeConnectStatus(c.Status.CONNECTED,null)):"error"==a.getAttribute("type")&&(c.info("Session creation failed."),this._changeConnectStatus(c.Status.AUTHFAIL,null));return!1},_sasl_failure_cb:function(a){this._sasl_success_handler&&(this.deleteHandler(this._sasl_success_handler),this._sasl_success_handler=null);this._sasl_challenge_handler&&(this.deleteHandler(this._sasl_challenge_handler),this._sasl_challenge_handler=null);this._changeConnectStatus(c.Status.AUTHFAIL,null);return!1},_auth2_cb:function(a){"result"==
a.getAttribute("type")?(this.authenticated=!0,this._changeConnectStatus(c.Status.CONNECTED,null)):"error"==a.getAttribute("type")&&(this._changeConnectStatus(c.Status.AUTHFAIL,null),this.disconnect());return!1},_addSysTimedHandler:function(a,b){var d=new c.TimedHandler(a,b);d.user=!1;this.addTimeds.push(d);return d},_addSysHandler:function(a,b,d,m,l){a=new c.Handler(a,b,d,m,l);a.user=!1;this.addHandlers.push(a);return a},_onDisconnectTimeout:function(){c.info("_onDisconnectTimeout was called");for(var a;0<
this._requests.length;)a=this._requests.pop(),a.abort=!0,a.xhr.abort(),a.xhr.onreadystatechange=function(){};this._doDisconnect();return!1},_onIdle:function(){for(var a,b,d,l;0<this.removeTimeds.length;)b=this.removeTimeds.pop(),a=this.timedHandlers.indexOf(b),0<=a&&this.timedHandlers.splice(a,1);for(;0<this.addTimeds.length;)this.timedHandlers.push(this.addTimeds.pop());var p=(new Date).getTime();l=[];for(a=0;a<this.timedHandlers.length;a++)if(b=this.timedHandlers[a],this.authenticated||!b.user)d=
b.lastCalled+b.period,0>=d-p?b.run()&&l.push(b):l.push(b);this.timedHandlers=l;this.authenticated&&0===this._requests.length&&0===this._data.length&&!this.disconnecting&&(c.info("no requests during idle cycle, sending blank request"),this._data.push(null));if(2>this._requests.length&&0<this._data.length&&!this.paused){b=this._buildBody();for(a=0;a<this._data.length;a++)null!==this._data[a]&&("restart"===this._data[a]?b.attrs({to:this.domain,"xml:lang":"en","xmpp:restart":"true","xmlns:xmpp":c.NS.BOSH}):
b.cnode(this._data[a]).up());delete this._data;this._data=[];this._requests.push(new c.Request(b.tree(),this._onRequestStateChange.bind(this).prependArg(this._dataRecv.bind(this)),b.tree().getAttribute("rid")));this._processRequest(this._requests.length-1)}0<this._requests.length&&(a=this._requests[0].age(),null!==this._requests[0].dead&&this._requests[0].timeDead()>Math.floor(c.SECONDARY_TIMEOUT*this.wait)&&this._throttledRequestHandler(),a>Math.floor(c.TIMEOUT*this.wait)&&(c.warn("Request "+this._requests[0].id+
" timed out, over "+Math.floor(c.TIMEOUT*this.wait)+" seconds since last activity"),this._throttledRequestHandler()));clearTimeout(this._idleTimeout);this._idleTimeout=setTimeout(this._onIdle.bind(this),100)}};r&&r(c,q,s,l,t)})(function(r,q,s,l,t){window.Strophe=r;window.$build=q;window.$msg=s;window.$iq=l;window.$pres=t});
